server:
  port: 8001
  ssl:
    enabled: false
security:
  basic:
    enabled: false
management:
  security:
    enabled: false

spring:
  application:
    name: gateway
    default-domain: gateway
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveResponseHeader=Set-Cookie
        - AddRequestHeader=Host, ${request.host}
      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1/**
          filters:
            - PreserveHostHeader
            - RewritePath=/service1/(?<segment>.*), /${segment}
        - id: service2
          uri: lb://service2
          predicates:
            - Path=/service2/**
          filters:
            - PreserveHostHeader
            - RewritePath=/service2/(?<segment>.*), /${segment}
  jmx:
    enabled: false

endpoints:
  enabled: false
  jmx:
    enabled: false
    domain: gateway
  env:
    enabled: false

eureka:
  server:
    port: 8000
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:${eureka.server.port}/eureka
  instance:
    metadataMap:
      instanceId: gateway
      zone: zone1
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3

loadbalancer:
  extensions:
    propagation:
      keys:
        - version
        - favorite-zone
        - upstream-zone