server:
  port: 8031
  ssl:
    enabled: false
security:
  basic:
    enabled: false
management:
  security:
    enabled: false

spring:
  application:
    name: service3
    default-domain: service3-zone1
  cloud:
    config:
      enabled: false
  jmx:
    enabled: false

endpoints:
  enabled: false
  jmx:
    enabled: false
    domain: service3-zone1
  env:
    enabled: false

eureka:
  server:
    port: 8000
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:${eureka.server.port}/eureka
  instance:
    metadataMap:
      instanceId: service3-zone1
      zone: zone1
      version: 1.0.0
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3

loadbalancer:
  extensions:
    propagation:
      keys:
        - version
        - favorite-zone
        - upstream-zone